export const SET_WEDDING_INFO = 'SET_WEDDING_INFO';
export const ADD_SHARED_ALBUM = 'ADD_SHARED_ALBUM';
export const ADD_ATTENDEE = 'ADD_ATTENDEE';
export const ADD_GUESTBOOK_ENTRY = 'ADD_GUESTBOOK_ENTRY';
export const SET_GROOM_INFO = 'SET_GROOM_INFO';
export const ADD_GROOM_FAMILY_MEMBER = 'ADD_GROOM_FAMILY_MEMBER';
